### PR TITLE
Twemoji support using Twemoji Awesome

### PR DESCRIPTION
**Pull request by chipset95**
Added [Twemoji](http://twitter.github.io/twemoji/) support using [Twemoji Awesome](http://ellekasai.github.io/twemoji-awesome/). Added documentation for the same.

### CODE REVIEW

**Comment by njaremko** [comment]
While Twemoji is great, I'm not sure it's worth implementing in the master branch. Importing the css takes 30 seconds for someone that needs it, and including it by default slows down page load times.

**Comment by PanosSakkos** [comment]
That's something I also wanted to discuss :smile: 

I suggest to implement it under a liquid condition.
Then the forkers can just enable it from the site config.

That way, we will not affect the default performance of the theme, and at the same time we can offer a very easy way to everyone to turn this feature on :smile: 

@njaremko what do you think?

**Comment by chipset95** [comment]
How about adding a boolean in `_config.yml` and check for it in `head.html` to include the css or not. Adding a js function which can read emoticons like `:P` and replace it with appropriate `<i>` tag could be an option too.

**Comment by njaremko** [comment]
If you're going to implement it. It's probably easiest to make a separate extras.html that can hold non-standard functionality, and we just comment out everything inside (let users uncomment the functionality that they want).

Then we just add:
{% include extras.html %} to the index (Possibly even comment that out as well)

**Comment by PanosSakkos** [comment]
What about starting an IRC channel for the contributors of the repository? :smile: 

cc @joariasl @eiselems @prashantsolanki3

**Comment by joariasl** [comment]
All right. It will be more fun.
Something like Gitter?

**Comment by PanosSakkos** [comment]
Oh gitter looks great, I hadn't heard it before! :smile: 

I will create a channel and invite you :smile:

**Comment by PanosSakkos** [comment]
Done! :wink:

**Comment by njaremko** [comment]
So, back to the pull request... :stuck_out_tongue_winking_eye: 

What do you think? @PanosSakkos @chipset95

**Comment by chipset95** [comment]
Emojione looks good. `.toImage(str)` can be used to convert both shortname and the unicode to images. I'll try to implement it soon, got an exam tomorrow. :stuck_out_tongue:

**Comment by PanosSakkos** [comment]
@njaremko I didn't have time so far to think about it, but I will come back to it soon :smile:

**Comment by chipset95** [comment]
I'm closing this now. We'll discuss how to implement this and do that in a fresh checkout. Otherwise things might break since this PR branch is already 62 commits behind.

**Comment by joariasl** [comment]
@chipset95 This is not a problem. Git is very intelligently and detect the difference automatically and if exist a problem it is solved with recursive method.
I looked your changes and this should not generate problem.

**Pull request closed without merging**
