### PR TITLE
Justify post and latest post preview

### PR DESCRIPTION
**Pull request by PanosSakkos**
## Proposed Changes

  - Justify the post content, instead of being centered
  - Justify the latest post preview, instead of being centered

Makes the content easier to read. What do you think @joariasl @eiselems ?

### CODE REVIEW

**Comment by eiselems** [comment]
For me everything is better than being centered :D

**Comment by PanosSakkos** [comment]
@eiselems I find the justified text easier to read actually 😋 

Let's take it to a vote, @joariasl which text alignment do you prefer for the posts content, left aligned or justified? 😄

**Comment by eiselems** [comment]
@PanosSakkos justify it :) The left-aligning was just a quick fix - better should justify it too

**Comment by joariasl** [comment]
I think that the left it's better that the centered alignment for read.

**Pull request merged**
