### PR TITLE
Issue Fixed #206

### LINKED ISSUE #206: Option for configure main picture from social networks profile images
## Expected Behavior
Integration for configure the main picture from social networks profile images.

## Actual Behavior
Only local file picture is implemented.

## Steps to Reproduce the Issue
Inclution for:
  1. LinkedIn
  2. Facebook
  3. Twitter
  3. Gravatar

### PR DESCRIPTION
**Pull request by manas94gupta**
Issue Fixed #206

## Proposed Changes
  - Add an option to connect the main picture to social profile images from facebook and github.               
  - Updated modifying header blog post with the instructions.                         
  - Tested on both desktop and mobile with multiple accounts.

### CODE REVIEW

**Comment by manas94gupta** [comment]
I implemented for twitter as well but the issue is that it only works on desktop.On mobile, the url redirects to mobile site so it doesn't retrieves the image.                         
I'll try to implement for gravatar but I think a proper implementation for twitter and linkedin is only possible through their api.

**Comment by manas94gupta** [comment]
I have implemented for gravatar as well. It  is working fine on all devices. I'll close this request and create a new one. Wouldn't mark the issue as fixed this time, since there are still some networks missing.

**Comment by PanosSakkos** [comment]
@joariasl why didn't we break the issue down into different social networks? That's good work that we could potentially miss 😄  Good stuff @manas94gupta !

**Comment by manas94gupta** [comment]
Thanks @PanosSakkos .
Breaking the issue into different networks seems like a good idea.

**Pull request closed without merging**
