### PR TITLE
Update grayscale.scss

### PR DESCRIPTION
**Pull request by joariasl**
min-height is the correct definition for not reduce the height if the parent size is less.

### CODE REVIEW

**Comment by PanosSakkos** [comment]
Can you please post a screenshot with the repro? :smile:

**Comment by joariasl** [comment]
The problem is when the parent height is less that the div for swipe instruction.
I used a cyan color for show the difference.
Before:
screenshot from 2015-11-25 17-16-09
After:
screenshot from 2015-11-25 17-18-48

With the min-height propriety if the parent is less, the size use the auto content size, but if the parent is major, the div use the 100% of the parent size.

**Comment by joariasl** [comment]
I see that is necessary separate the container for the text of the post with the content for another content.

**Comment by PanosSakkos** [comment]
And let's track is by an issue as well :wink: 

The workflow is:

 1. Open issue with repro steps and screenshot
 2. And then open the PL referencing the issue number :wink: 

I will try to see the PLs tonight, but I can't promise anything because I've been busy lately :(

Thanks!

**Pull request merged**
