### PR TITLE
Fix for #100

### PR DESCRIPTION
**Pull request by chipset95**
Uses `jekyll.environment` value to enable or disable disqus and google analytics on serve

### CODE REVIEW

**Comment by PanosSakkos** [comment]
How is the production variable set when building? something like:

 jekyll build --environment "production" ?

**Comment by chipset95** [comment]
I'm looking into it

**Comment by chipset95** [comment]
I added `JEKYLL_ENV=production` before the serve script in travis, it works :)

**Comment by PanosSakkos** [comment]
Great! :smile: 

The last thing we have to figure out is how GitHub Pages is building the website.
Will it use the production value while building?

**Comment by chipset95** [comment]
GitHub sets it to production always.

**Comment by PanosSakkos** [comment]
I'm thinking out loud here.

What we are trying to do here is not right.
Because when we are serving locally we are actually (manually) testing our changes as well.
Which means that if we introduce this toggling of the features then the built website that we will be testing will not be the same as the one that it will be served in production.

Of course iteration agility matters, but what it matters most is to be able to test the website effectively.

I propose to include the production variable in the /scripts/serve and add a new script (i.e. /scripts/quick-serve) that will be for the advanced users that want to have quick dev iterations :wink:

**Comment by chipset95** [comment]
@PanosSakkos There's no point in creating hits for GA when serving locally. And Disqus creates a problem with multiple threads. It happened for me, user's were getting redirected to localhost instead of the actual url. This is just disabling GA and Disqus, everything else remains the same. 

What we can have is create a script which serves with environment as productions, which can be used to check the site before pushing to github.

**Comment by PanosSakkos** [comment]
> What we can have is create a script which serves with environment as productions, which can be used to check the site before pushing to github.

Yes, we agree! :yum: 

But we should have two scripts, the /scripts/serve and /scripts/quick-serve, that's what I wanted to communicated earlier :wink:

**Comment by joariasl** [comment]
You are use the detection of local or 127.0.0.1 siteurl

**Comment by PanosSakkos** [comment]
@chipset95 not 100 issues, but 100 fixes! :smile: :wink:

**Pull request merged**
