### PR TITLE
Minified typed.js

### PR DESCRIPTION
**Pull request by njaremko**
Totally forgot, we should probably also minify typed.js.......

### CODE REVIEW

**Comment by PanosSakkos** [comment]
No worries! 

Given that this script is not loaded in a new request (like grayscale.js was), does it make sense to minify it? We will just save a few bytes of data like this. Right? Or did I misunderstood something? :smile:

**Comment by PanosSakkos** [comment]
Just noticed that the typed.js file is included from the includes/js.html file...

Merging! :smile:

**Comment by PanosSakkos** [comment]
I inlined it as well 61705ab97d3b49ec5416f79831bb0a88f2b7efc0 :smile:

**Comment by njaremko** [comment]
Every bit counts, always minify! :stuck_out_tongue_winking_eye: 
From what I've read, you're only supposed to inline small amounts of javascript.
Apparently files that are imported are cached by the browser, but in-lined javascript isn't.

**Comment by PanosSakkos** [comment]
As you wish Minify Police! :yum: 

I see, then it makes sense to revert my inline check-in :smile:

**Comment by PanosSakkos** [comment]
Reverted 81b5b979994a8c37c56dc6fe3d79deb7dac57da8

**Pull request merged**
