### PR TITLE
Personal jekyll theme

### PR DESCRIPTION
**Pull request by bgoldman**
What a great Jekyll theme! Here are a bunch of updates to make this even more useful, which I've already implemented on my own website.

Here is a summary of changes:

**Important**
1. Run Jekyll in watch mode so that you don't need to restart it every time you make changes
2. Add category pages, which are similar to tag pages, but for the post's category rather than its many tags
3. Add author blurb functionality to post a picture and mini-bio beneath all blog posts
4. Fix blocking bug where HTTPS is forced on localhost regardless of config setting

**Spring Cleaning**
1. Centralize the social footer link code so it's not duplicated in five places unnecessarily
2. Update typed.js to the newest version
3. Misc code style cleanup
4. Clarify on homepage that the latest blog post is the latest and not just a blog with only one article on it (someone thought that about my blog, for example)
5. Hid the Disqus JS when running on localhost, to get rid of those pesky console.log errors

**Config**
1. Change Google Analytics default to use a fake string rather than your real account
2. Change Disqus defualt to use a fake username rather than your real account
3. Remove duplicate 404 image declaration

### CODE REVIEW

**Comment by PanosSakkos** [comment]
Let's open one issue per feature, so we can discuss each feature independently :wink: 

Of course we will need to break down this PL as well, but let's start from discussing what we what to take, what not, and the reason :smile:

**Comment by PanosSakkos** [comment]
I'm taking in the critical bug fixes with cherry-pick and amend (in order to keep the format "Fixes #issue")

And then I will open the issues for the feature requests so we can discuss them separately :smile:

**Comment by PanosSakkos** [comment]
>Important
>1. Run Jekyll in watch mode so that you don't need to restart it every time you make changes

Merged

>2. Add category pages, which are similar to tag pages, but for the post's category rather than its many >tags

Merged (Great work! :clap:)

>3. Add author blurb functionality to post a picture and mini-bio beneath all blog posts

Loved it! But I rat out of time, will merge it next weekend :smile: 

>4. Fix blocking bug where HTTPS is forced on localhost regardless of config setting

Merged.

>Spring Cleaning
>1. Centralize the social footer link code so it's not duplicated in five places unnecessarily

Merged.

>2. Update typed.js to the newest version

Merged.

>3. Misc code style cleanup

Merged.

>4. Clarify on homepage that the latest blog post is the latest and not just a blog with only one article on >it (someone thought that about my blog, for example)

Merged

>5. Hid the Disqus JS when running on localhost, to get rid of those pesky console.log errors

Merged

>Config
>1. Change Google Analytics default to use a fake string rather than your real account

Didn't merge it, because I'm trying to keep an eye on the traffic of the page. I know that it's not reliable, but it's better than nothing :smile: 

>2. Change Disqus default to use a fake username rather than your real account

Merged 

>3. Remove duplicate 404 image declaration

Merged

**Comment by bgoldman** [comment]
Awesome. I'm pleasantly surprised that you merged almost all of it and only rejected one and postponed another :) From your initial response I thought you might reject more than that and was wondering which ones! I'm really glad that you found value in the work I did, and I hope to contribute more in the future.

**Comment by PanosSakkos** [comment]
Actually I never had time to have even a quick look at it! 

But in general I have battle scars from the past, so I'm trying to communicate the process of proposing features and discussing them before diving into the code and opening the PL.

I understand that you just started hacking your own features and fixes and after a while you realized that they are valuable, so no worries about it :wink:

**Comment by PanosSakkos** [comment]
Merge the Author Blurb as well. I'm closing the PL :wink:

**Comment by bgoldman** [comment]
:100:

**Pull request closed without merging**
