### PR TITLE
Implementing SASS, mailto JavaScript protection and XHTML to HTML definition

### PR DESCRIPTION
**Pull request by joariasl**
Change CSS Style definition to SASS.
Minification of CSS builded.
Improvements in JavaScript definition.
JavaScript mailto protection.
Changing in practices document definition for best W3C validation.

### CODE REVIEW

**Comment by PanosSakkos** [comment]
Hi!

I will test it during the weekend (hopefully) and will merge it if everything is ok :smile: 

Thanks!

**Comment by joariasl** [comment]
Thank you!
Great contribution. I hope I have contributed something.

**Comment by PanosSakkos** [comment]
Thanks! You are indeed contributing ;)

Can you please move the join_at_email javascript in the _includes/js.html? 
The purpose is to keep all the js scripts at the end of the html.

**Comment by PanosSakkos** [comment]
I noticed that you introduced a new variable in the config, regarding the language. 
Can you please document its use in the readme? Otherwise nobody will notice this feature ;)

**Comment by joariasl** [comment]
The join_at_mail function is for hide plain text of the mail and avoid Spam bots if use direct mail in mailto.
This function is only used in index.html, which is why I put it there. You must also write directly to that position and preferably is best done direct.

**Comment by joariasl** [comment]
The setting for SASS minification must be specified, otherwise it will not.

**Comment by joariasl** [comment]
Changes applied. CND is always used, they have eliminated local resources and configuration lang variable is described.

**Comment by joariasl** [comment]
Dear.
I remember this Pull Request.

**Comment by PanosSakkos** [comment]
Hi! I will have a look today, I promise :)

I take care of the github projects during weekends, because I'm a bit busy :)

**Comment by PanosSakkos** [comment]
Hi,

You missed a few points from the first comments:

1. Delete fonts/ directory (it's empty)
2. Move the join_at_email declaration in the js.html (it's important because the js.html file is included at the end of the html code)
3. Why did you keep the sass style definition in the config file? I mean everyone will want the compressed option, so why increasing the size of the config with something redundant? :)
4. Why did you change the event description of the career to a div? This made the text grey instead of white, and white was selected because on black background it makes the text more friendly to the eyes.

**Comment by joariasl** [comment]
1. The fonts directory is deleted before
2. This function is only used in index.html. The function must be declared before as it is used in rendering period and not after loading the DOM.
3. The setting for SASS minification must be specified, otherwise it will not. It is not redundant.
4. Solved. There was an error return there before. was produced <p> tag within a <p> tag, then the class was implicitly omitted when rendering. Removed <p> tag, this makes markdownify.

**Comment by joariasl** [comment]
View:
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.jorgearias.cl%2F
vs
https://validator.w3.org/check?uri=http%3A%2F%2Fpanossakkos.github.io%2F&charset=%28detect+automatically%29&doctype=Inline&group=0

or

https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.jorgearias.cl%2F&tab=desktop
vs
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fpanossakkos.github.io%2F&tab=desktop

**Comment by PanosSakkos** [comment]
Great! Thanks for the contribution!

**Comment by joariasl** [comment]
:D

**Pull request merged**
