### PR TITLE
Fixes #98

### LINKED ISSUE #98: Incorrect start_url
`start_url` in `manifest.json` inside `_site` if empty is `baseurl` is kept empty in `_config.yml`

Suggestion for fix:

Change `"start_url": "{{site.baseurl}}"` to `"start_url": "{{site.url}}{{site.baseurl}}"`

### PR DESCRIPTION
**Pull request by chipset95**
Attempt to fix #98

### CODE REVIEW

**Comment by PanosSakkos** [comment]
I will take the risk to merge it without testing it on my Android.
Because I saw this bug yesterday and the fix looks correct :smile: 
I want to avoid the case where someone forks the repo and the web app feature on android is broken...

**Comment by chipset95** [comment]
It was broken for me. I tested it both on a user page and gh-page. It was working

**Comment by PanosSakkos** [comment]
I trust you then :wink:

**Comment by PanosSakkos** [comment]
Double checked on my Android and it resolved the issue :wink: 

Good judgement call :sunglasses:

**Pull request merged**
