### PR TITLE
Intro Background Animations added

### PR DESCRIPTION
**Pull request by prashantsolanki3**
Color gradient
Simple Bg image
3d lines.

### CODE REVIEW

**Comment by PanosSakkos** [comment]
Great contribution! :+1: 

Let's add its documentation [here](https://panossakkos.github.io/personal-jekyll-theme/tech/2015/06/24/intro-layout-tutorial.html). 

// Documenting features is as important as the feature itself, since people need to know about them and know how to use them :wink:

**Comment by PanosSakkos** [comment]
[Bug](https://dl.dropboxusercontent.com/u/8522559/personal-jekyll-theme/bugs/mobile.tiff) bashing! :smile:

**Comment by PanosSakkos** [comment]
Bug bashing! Maybe @joariasl can help you on how to fix it :wink: 



:smile:

**Comment by joariasl** [comment]
Solved in #76

**Comment by PanosSakkos** [comment]
Continued in https://github.com/PanosSakkos/personal-jekyll-theme/pull/77

**Pull request closed without merging**
