### PR TITLE
Readme and documentation update

### PR DESCRIPTION
**Pull request by chipset95**

### CODE REVIEW

**Comment by PanosSakkos** [comment]
I'm closing this since I merged the correct PL :wink:

**Comment by chipset95** [comment]
That one was for gh-pages, this one is for master. The commit is same

**Comment by PanosSakkos** [comment]
Oh, I didn't notice it :smile: I will fix the mess :smile: 

Don't worry about the gh-pages branch since I keep updating it :wink: Thanks for being proactive! :smile:

**Comment by chipset95** [comment]
Took a break from studies and noticed that you hadn't merged e309297 in gh-pages, so I did that

**Comment by PanosSakkos** [comment]
I updated master, did a checkout on gh-pages and force-pushed to origin :smile:

**Comment by chipset95** [comment]
That works too, haha :laughing:

**Comment by PanosSakkos** [comment]
It's a quick way to keep the gh-pages branch up to date :wink:

**Pull request merged**
