### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by skeledrew**
Issue Fixed #

## Proposed Changes

  -
  -
  -

Added a workaround to remove forked status, which was preventing github from publishing the site.

### CODE REVIEW

**Comment by skeledrew** [comment]
This is my first GitHub pull request. Hope I'm not breaking etiquette, etc.

**Comment by PanosSakkos** [comment]
Hi. Why removing the forked tidbit? That would hurt the visibility of the repository :anguished:

**Comment by skeledrew** [comment]
Unfortunately that's the only way GitHub would publish the site. However, I still keep the original repo.

**Comment by PanosSakkos** [comment]
Here is a [fork](https://github.com/alexgalatoulas/alexgalatoulas.github.io) and the corresponding published [website](http://alexgalatoulas.github.io)

Let me know if I misunderstood your issue :smile:

**Comment by skeledrew** [comment]
Hmm. Maybe something was wrong with my changes or there's something I didn't understand. I did a fork and rename as well, but the site wasn't accessible at skeledrew.github.io while it had forked status. I think I'd read somewhere too that GH pages should be orphans for it to work.

**Pull request closed without merging**
